# Громкость и перемотка
WHEEL_UP    add volume 2
WHEEL_DOWN  add volume -2
UP          add volume 2
DOWN        add volume -2
RIGHT       seek 5
LEFT        seek -5
Shift+RIGHT seek 30
Shift+LEFT  seek -30

# Плейлист и повтор
l           cycle-values loop-file "inf" "no"
n           playlist-next
p           playlist-prev
PGUP        playlist-prev
PGDWN       playlist-next

# Магия UOSC
m           script-binding uosc/menu
s           script-binding uosc/subtitles
a           script-binding uosc/audio
v           script-binding uosc/video
o           script-binding uosc/open-file
alt+p       script-binding uosc/playlist
ctrl+s      async screenshot
