# Подключаем тему Stylix
include="~~/stylix.conf"

# Качество видео и рендеринг
profile=gpu-hq
vo=gpu
gpu-context=wayland
hwdec=auto-safe

# Масштабирование
scale=ewa_lanczossharp
cscale=mitchell
dscale=mitchell
dither-depth=auto
correct-downscaling=yes
linear-downscaling=yes

# Поведение
save-position-on-quit=true
keep-open=yes
sub-auto=fuzzy

# Интерфейс
osc=no
osd-bar=no
border=no
cursor-autohide=1000

# Исправление выхода за границы экрана
# autofit-larger=99%x99%
geometry=99%x96%

# Настройки геометрии (уже в input.conf или тут)
# geometry=99%x96%
