# Цвета и прозрачность (прозрачность тут, цвета в Stylix)
opacity=0.9,chapters=1
menu_opacity=0.9

# Масштабирование
scale=1
scale_fullscreen=1.5

# Зоны чувствительности (в пикселях)
# proximity_in=100
# proximity_out=200

# Общее поведение
progress=always

# Таймлайн
timeline_size=40
timeline_border=1
timeline_persistency=paused,hover
chapter_range_indicators=always

# Верхняя панель
top_bar=always
top_bar_title=yes
top_bar_controls=yes

# Превью
timeline_thumbnails=yes

# Отключаем подстройку полей
adjust_osd_margins=no
