# --- Главное ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # поддержка undercurl
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Меняем префикс на Alt + a
set -g prefix M-a
unbind C-b
bind M-a send-prefix

# Включаем мышь
set -g mouse on

# Начинаем отсчет окон и панелей с 1 (а не с 0)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -sg escape-time 0 # убираем задержку Esc (важно для Vim)
set -g focus-events on

# --- Навигация ---

# Быстрое переключение панелей (Alt + h,j,k,l) без префикса
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Изменение размера панелей стрелочками (Prefix + стрелка)
bind -r Left resize-pane -L 5
bind -r Down resize-pane -D 5
bind -r Up resize-pane -U 5
bind -r Right resize-pane -R 5

# Изменение размера панелей (Prefix + H,J,K,L)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Интуитивные сплиты
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Закрыть панель (q - quit)
bind q confirm-before -p "Kill pane? (y/n)" kill-pane

# Перезагрузка конфига (r - reload)
bind r source-file ~/.tmux.conf \; display-popup -E "echo ' Config Reloaded! ' && sleep 0.5"

# Сохраняем текущий путь при создании нового окна
bind c new-window -c "#{pane_current_path}"

# Синхронизация панелей (Prefix + S)
bind S set-window-option synchronize-panes

# --- Оформление (Status Bar) ---
set -g status-position top
set -g status-style "bg=default"

set -g status-left-length 60
set -g status-left "#[fg=blue,bold,bg=default] 󰭓 #S #[fg=brightblack,nobold] "

set -g status-right-length 120
set -g status-right "#[fg=brightblack] #[fg=white]󰃭 %d-%m #[fg=brightblack] #[fg=magenta,bold]󱑎 %H:%M #[fg=brightblack] #[fg=blue]󰒋 #h "

setw -g window-status-current-format "#[fg=cyan,bold] 󱓟 #I:#W* "
setw -g window-status-format "#[fg=brightwhite,nobold] #I:#W  "
setw -g window-status-separator ""

set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"

# --- Режим Vim (Copy Mode) ---
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# выделение не пропадает при отпускании кнопки мыши
unbind -T copy-mode-vi MouseDragEnd1Pane

# Попап Scratchpads
bind T display-popup -E -w 85% -h 85% "btop"
bind Space display-popup -E -w 90% -h 90%

# --- Плагины (через TPM) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-sessionx' # мощный поиск по сессиям

# Настройки tmux-yank
set -g @override_copy_command 'wl-copy'
set -g @yank_selection_mouse 'clipboard'

# Настройки sessionx (Prefix + o)
set -g @sessionx-bind 'o'
set -g @sessionx-window-mode 'on'
set -g @sessionx-layout 'window'

# Авто-сохранение сессий
set -g @continuum-restore 'on'

# Инициализация менеджера плагинов (должна быть в самом конце)
run '~/.tmux/plugins/tpm/tpm'

